swagger: "2.0"
info:
  version: "3.0.0"
  title: FFAStrans REST API Version 3.0
# during dev, should point to your local machine
#host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
#schemes:
  # tip: remove http to make production-grade
#  - http
#  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /getjoblog:
    # binds a127 app logic to a route
    x-swagger-router-controller: get_job_log
    get:
      description: Gets an existing jobs log file contents
      # used as the method name of the controller
      operationId: get_job_log
      parameters:
        - name: jobid
          in: query
          description: A JobId, currently all branches of a job share the same jobid, getjoblog cannot determine which log line belongs to which branch
          required: true
          type: string
      responses:
        "200":
          description: Success

        # responses may fall through to errors
        default:
          description: Error
  /getjobdetails:
    # binds a127 app logic to a route
    x-swagger-router-controller: get_job_details
    get:
      description: Get all available details about an existing job
      # used as the method name of the controller
      operationId: get_job_details
      parameters:
        - name: jobid
          in: query
          description: A JobId, currently all branches of a job share the same jobid, getjoblog cannot determine which log line belongs to which branch
          required: true
          type: string
      responses:
        "200":
          description: Success

        # responses may fall through to errors
        default:
          description: Error
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
